// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    // Backtop: typeof import('./src/components/Backtop.vue')['default']
    // Carousel: typeof import('./src/components/Carousel.vue')['default']
    // ElButton: typeof import('element-plus/es')['ElButton']
    // ElCarousel: typeof import('element-plus/es')['ElCarousel']
    // ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    // ElDropdown: typeof import('element-plus/es')['ElDropdown']
    // ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    // ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    // ElIcon: typeof import('element-plus/es')['ElIcon']
    // ElInput: typeof import('element-plus/es')['ElInput']
    // ElOption: typeof import('element-plus/es')['ElOption']
    // ElSelect: typeof import('element-plus/es')['ElSelect']
    // HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    // Head: typeof import('./src/views/layout/Head.vue')['default']
    // Left: typeof import('./src/views/layout/Left.vue')['default']
    // Content: typeof import('./src/views/layout/Content.vue')['default']
    // Right: typeof import('./src/views/layout/Right.vue')['default']

  }
}
export { }
